let backupDirHandle = null, backupMeta = []; const BACKUP_META = '做题引擎备份_meta.json', MAX_BACKUPS = 10;
function openHandleDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open('QuizEngineDirHandle',1);r.onupgradeneeded=()=>r.result.createObjectStore('handles');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function storeDirHandle(h){const db=await openHandleDB();const tx=db.transaction('handles','readwrite');tx.objectStore('handles').put(h,'backupDir');await new Promise(r=>{tx.oncomplete=r;tx.onerror=r;});db.close();}
async function loadDirHandle(){try{const db=await openHandleDB();const tx=db.transaction('handles','readonly');const r=tx.objectStore('handles').get('backupDir');return new Promise((resolve,reject)=>{r.onsuccess=()=>{db.close();resolve(r.result);};r.onerror=()=>{db.close();reject(r.error);};});}catch(e){return null;}}
async function clearDirHandle(){const db=await openHandleDB();const tx=db.transaction('handles','readwrite');tx.objectStore('handles').delete('backupDir');await new Promise(r=>{tx.oncomplete=r;tx.onerror=r;});db.close();}
function updateBackupStatus(msg,type){const el=document.getElementById('backup-status');if(el){el.textContent=msg;el.style.color=type==='ok'?'#2ed573':type==='warn'?'#f59e0b':'#666';}}
async function openBackupDialog(){const status=document.getElementById('backup-current-status');const actions=document.getElementById('backup-dialog-actions');status.innerHTML='🔍 检测中...';actions.innerHTML='';const handle=await loadDirHandle();if(handle){try{const perm=await handle.queryPermission({mode:'readwrite'});if(perm==='granted'){backupDirHandle=handle;status.innerHTML='✅ 当前备份位置：<strong>'+escapeHtml(handle.name)+'</strong>';actions.innerHTML='<button class="btn btn-warning btn-small" onclick="changeBackupFolder()">🔄 更改</button><button class="btn btn-secondary btn-small" onclick="closeBackupDialog()">关闭</button>';await refreshBackupMeta();document.getElementById('backup-dialog').classList.add('active');return;}}catch(e){}await clearDirHandle();}status.innerHTML='📂 尚未设置备份文件夹。<br><span style="color:#888;font-size:13px;">选择后自动备份。</span>';actions.innerHTML='<button class="btn btn-primary btn-small" onclick="setupBackupFromDialog()">📂 选择文件夹</button><button class="btn btn-secondary btn-small" onclick="closeBackupDialog()">关闭</button>';document.getElementById('backup-dialog').classList.add('active');}
function closeBackupDialog(){document.getElementById('backup-dialog').classList.remove('active');}
async function setupBackupFromDialog(){if(!window.showDirectoryPicker){alert('⚠️ 请使用 Chrome/Edge');return;}try{const handle=await window.showDirectoryPicker({mode:'readwrite'});backupDirHandle=handle;await storeDirHandle(handle);updateBackupStatus('✅ 已设置: '+handle.name,'ok');await refreshBackupMeta();closeBackupDialog();alert('✅ 备份文件夹已设置');if(ucCurrentScreen==='data')renderDataPage();}catch(e){if(e.name!=='AbortError')alert('❌ 设置失败');}}
async function changeBackupFolder(){await clearDirHandle();backupDirHandle=null;await setupBackupFromDialog();}
async function refreshBackupMeta(){if(!backupDirHandle)return;try{const mh=await backupDirHandle.getFileHandle(BACKUP_META).catch(()=>null);if(mh)backupMeta=JSON.parse(await (await mh.getFile()).text());else backupMeta=[];updateBackupStatus('✅ '+backupMeta.length+' 份备份','ok');if(ucCurrentScreen==='data')renderDataPage();}catch(e){backupMeta=[];updateBackupStatus('✅ 就绪','ok');if(ucCurrentScreen==='data')renderDataPage();}}
async function doManualBackup(){if(!backupDirHandle){alert('请先设置备份文件夹');return;}updateBackupStatus('⏳ 备份中...');await autoBackup();}
async function autoBackup(){if(!backupDirHandle)return;try{const perm=await backupDirHandle.requestPermission({mode:'readwrite'});if(perm!=='granted'){updateBackupStatus('⚠️ 权限失效','warn');backupDirHandle=null;await clearDirHandle();return;}let backups=[];try{const mh=await backupDirHandle.getFileHandle(BACKUP_META).catch(()=>null);if(mh)backups=JSON.parse(await (await mh.getFile()).text());}catch(e){backups=[];}const idx=backups.length+1;const ts=new Date();const tsStr=ts.getFullYear()+'-'+String(ts.getMonth()+1).padStart(2,'0')+'-'+String(ts.getDate()).padStart(2,'0')+' '+String(ts.getHours()).padStart(2,'0')+':'+String(ts.getMinutes()).padStart(2,'0');const filename='做题引擎备份_'+String(idx).padStart(3,'0')+'.json';const label='第'+idx+'次备份';const fh=await backupDirHandle.getFileHandle(filename,{create:true});const w=await fh.createWritable();await w.write(JSON.stringify({backupVersion:8,createdAt:ts.toISOString(),state},null,2));await w.close();backups.push({filename,label,timestamp:ts.toISOString(),dateStr:tsStr});while(backups.length>MAX_BACKUPS){const r=backups.shift();try{await backupDirHandle.removeEntry(r.filename);}catch(e){}}const mh2=await backupDirHandle.getFileHandle(BACKUP_META,{create:true});const w2=await mh2.createWritable();await w2.write(JSON.stringify(backups,null,2));await w2.close();backupMeta=backups;updateBackupStatus('✅ 备份: '+label,'ok');}catch(e){updateBackupStatus('⚠️ 备份失败: '+e.message,'warn');}}
async function tryAutoRestore(){if(location.protocol==='file:')return false;const handle=await loadDirHandle();if(!handle)return false;backupDirHandle=handle;await refreshBackupMeta();if(backupMeta.length===0)return false;const latest=backupMeta[backupMeta.length-1];try{const fh=await backupDirHandle.getFileHandle(latest.filename).catch(()=>null);if(!fh)return false;const data=JSON.parse(await (await fh.getFile()).text());if(data&&data.state){state=migrateState(data.state);saveState();updateBackupStatus('✅ 已恢复: '+latest.label,'ok');return true;}}catch(e){console.warn('auto restore err',e);}return false;}
async function openRestoreDialog(){if(!backupDirHandle||backupMeta.length===0){alert(backupDirHandle?'暂无备份':'请先设置备份文件夹');return;}await refreshBackupMeta();const container=document.getElementById('restore-list');if(backupMeta.length===0){container.innerHTML='<div class="empty-state">暂无备份</div>';}else{const sorted=[...backupMeta].reverse();container.innerHTML=sorted.map(b=>{const isLatest=b.filename===backupMeta[backupMeta.length-1].filename;return '<div class="restore-list-item"><div class="rli-info"><div class="rli-label">'+escapeHtml(b.label)+(isLatest?' ⭐最新':'')+'</div><div class="rli-date">'+escapeHtml(b.dateStr||b.timestamp)+'</div></div><button class="btn btn-small btn-warning" onclick="restoreFromBackup(\''+b.filename+'\')">⏪ 回档</button></div>';}).join('');}document.getElementById('restore-dialog').classList.add('active');}
function closeRestoreDialog(){document.getElementById('restore-dialog').classList.remove('active');}
async function restoreFromBackup(filename){if(!confirm('回档后当前数据将被替换。建议先做一次立即备份。'))return;try{const fh=await backupDirHandle.getFileHandle(filename);const data=JSON.parse(await(await fh.getFile()).text());if(!data||!data.state)throw new Error('格式错误');state=migrateState(data.state);saveState();closeRestoreDialog();renderSubjectList();const sids=Object.keys(state.subjects);if(sids.length>0){if(!state.currentSubjectId||!state.subjects[state.currentSubjectId])state.currentSubjectId=sids[0];const s=getSubj();if(s&&(!state.currentChapterId||!state.chapters[state.currentChapterId]))state.currentChapterId=s.chapterIds[0]||null;}const ch=getCh();if(ch&&ch.questions&&ch.questions.length>0){renderQuestion();updateProgress();}renderHistory();updateQuickActions();loadChapterStrategyToUI();showScreen(state.lastScreen||'start');updateBackupStatus('✅ 已回档','ok');alert('✅ 回档成功');}catch(e){alert('❌ 回档失败: '+e.message);}}